version: 2.1

orbs:
  slack: circleci/slack@4.1

parameters:
  workflow_id:
    type: string
    default: '${CIRCLE_WORKFLOW_ID:0:7}'

jobs:
  lint-code:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            pip install -r requirements.txt
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
  
  build-and-push-image:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo
    
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
      - run:
          name: Build docker image
          command: |
            ./run_docker.sh
      - run: 
          name: Push image to ECR
          command: |
            ./upload_docker.sh

  deploy-infrastructure:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install AWS CLI
          command: |
            tar
            # curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            # unzip awscliv2.zip
            # sudo ./aws/install
            # sudo pip install --upgrade pip
            # python3 -m pip install --user ansible
            
        
      
      
workflows:
  default:
    jobs:
      # - lint-code
      # - build-and-push-image:
      #    requires: [lint-code]
      - deploy-infrastructure
        #  requires: [build-and-push-image]

