version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |

            # python3 -m venv venv
            # . venv/bin/activate
            # make install
            # pip install -r requirements.txt
            # sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            # sudo chmod +x /bin/hadolint

            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws ecr get-login-password


      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # # run tests!
      # - run:
      #     name: run tests
      #     command: |
      #       . venv/bin/activate
      #       make test
      # # run lints!
      # - run:
      #     name: run lint
      #     command: |
      #       . venv/bin/activate
      #       make lint
